import { EmployeeListDataModel } from "src/app/modules/dashboard/modules/employee-list/shared/model/employee-list-data.model";

export const EMPLOYEE_DATABASE = [
    {
        id: 1,
        username: "pumpedcat",
        firstName: "Amber",
        lastName: "Lewis",
        email: "amber.r.lewis@ymail.com",
        birthDate: "1990-01-01",
        basicSalary: 8376200,
        status: "Active",
        group: "Staff",
        description: "2010-01-01"
    },
    {
        id: 2,
        username: "dampboot",
        firstName: "Kevin",
        lastName: "Kelly",
        email: "kevinkelly@yahoo.com",
        birthDate: "1988-07-25",
        basicSalary: 5448400,
        status: "Active",
        group: "Staff",
        description: "2012-07-25"
    },
    {
        id: 3,
        username: "publicfurniture",
        firstName: "Ava",
        lastName: "Mitchell",
        email: "ava_m_mitchell@aol.com",
        birthDate: "1970-04-18",
        basicSalary: 12715000,
        status: "Active",
        group: "Manager",
        description: "2010-04-18"
    },
    {
        id: 4,
        username: "somberfriend",
        firstName: "Rachel",
        lastName: "Rivera",
        email: "r_r_rivera@live.com",
        birthDate: "1999-11-12",
        basicSalary: 19532400,
        status: "Active",
        group: "Staff",
        description: "2019-11-12"
    },
    {
        id: 5,
        username: "earthycreature",
        firstName: "Ethan",
        lastName: "Murphy",
        email: "e_e@live.com",
        birthDate: "1987-04-09",
        basicSalary: 11219800,
        status: "Active",
        group: "Supervisor",
        description: "2012-04-09"
    },
    {
        id: 6,
        username: "jumbledriddle",
        firstName: "Sofia",
        lastName: "Thompson",
        email: "s.thompson@yahoo.com",
        birthDate: "1972-05-06",
        basicSalary: 18260700,
        status: "Active",
        group: "Supervisor",
        description: "2022-05-06"
    },
    {
        id: 7,
        username: "entertainingforce",
        firstName: "Dylan",
        lastName: "Rivera",
        email: "d.g.rivera@ymail.com",
        birthDate: "1988-09-22",
        basicSalary: 18310800,
        status: "Active",
        group: "Supervisor",
        description: "2012-09-22"
    },
    {
        id: 8,
        username: "breezyjeans",
        firstName: "Alexander",
        lastName: "Torres",
        email: "alexander_torres@live.com",
        birthDate: "1974-12-26",
        basicSalary: 5718700,
        status: "Active",
        group: "Manager",
        description: "2014-12-26"
    },
    {
        id: 9,
        username: "tritethunder",
        firstName: "Kyle",
        lastName: "Lee",
        email: "kylelee@hotmail.com",
        birthDate: "1975-01-04",
        basicSalary: 6471500,
        status: "Active",
        group: "Staff",
        description: "2023-01-04"
    },
    {
        id: 10,
        username: "woozyfeeling",
        firstName: "Michael",
        lastName: "Perez",
        email: "michael_j@gmail.com",
        birthDate: "1973-07-31",
        basicSalary: 18232100,
        status: "Active",
        group: "Manager",
        description: "2023-07-31"
    },
    {
        id: 11,
        username: "simplisticslope",
        firstName: "Kaitlyn",
        lastName: "Roberts",
        email: "kaitlyn_roberts@live.com",
        birthDate: "1989-03-14",
        basicSalary: 8114700,
        status: "Active",
        group: "Staff",
        description: "2014-03-14"
    },
    {
        id: 12,
        username: "eliteyam",
        firstName: "Emma",
        lastName: "Wood",
        email: "emmawood@yahoo.com",
        birthDate: "1970-10-03",
        basicSalary: 6896700,
        status: "Active",
        group: "Staff",
        description: "2019-10-03"
    },
    {
        id: 13,
        username: "colossalscarf",
        firstName: "Sophia",
        lastName: "Bryant",
        email: "smbryant@ymail.com",
        birthDate: "1975-12-15",
        basicSalary: 11730600,
        status: "Active",
        group: "Supervisor",
        description: "2017-12-15"
    },
    {
        id: 14,
        username: "quietmoney",
        firstName: "Isabella",
        lastName: "King",
        email: "isabella_lou20@gmail.com",
        birthDate: "1974-12-15",
        basicSalary: 15688400,
        status: "Active",
        group: "Manager",
        description: "2018-12-15"
    },
    {
        id: 15,
        username: "dullcontrol",
        firstName: "Zachary",
        lastName: "Kelly",
        email: "z_kelly@gmail.com",
        birthDate: "1974-10-14",
        basicSalary: 18449700,
        status: "Active",
        group: "Supervisor",
        description: "2019-10-14"
    },
    {
        id: 16,
        username: "gullibleroof",
        firstName: "Kayla",
        lastName: "Powell",
        email: "kayla_powell94@hotmail.com",
        birthDate: "1985-02-28",
        basicSalary: 14845000,
        status: "Active",
        group: "Supervisor",
        description: "2015-02-28"
    },
    {
        id: 17,
        username: "joyouscontrol",
        firstName: "Lillian",
        lastName: "Ramirez",
        email: "l.ramirez32@outlook.com",
        birthDate: "1997-02-05",
        basicSalary: 11853100,
        status: "Active",
        group: "Supervisor",
        description: "2017-02-05"
    },
    {
        id: 18,
        username: "uppitylamp",
        firstName: "Michael",
        lastName: "Brown",
        email: "michael.a@aol.com",
        birthDate: "1970-11-11",
        basicSalary: 9923300,
        status: "Active",
        group: "Supervisor",
        description: "2020-11-11"
    },
    {
        id: 19,
        username: "gulliblebucket",
        firstName: "Eric",
        lastName: "Bell",
        email: "ehbell@hotmail.com",
        birthDate: "1973-10-31",
        basicSalary: 18048700,
        status: "Active",
        group: "Manager",
        description: "2023-10-31"
    },
    {
        id: 20,
        username: "priceyriddle",
        firstName: "Emma",
        lastName: "Henderson",
        email: "eghenderson@gmail.com",
        birthDate: "1993-12-29",
        basicSalary: 15390300,
        status: "Active",
        group: "Manager",
        description: "2013-12-29"
    },
    {
        id: 21,
        username: "hungryswim",
        firstName: "Brandon",
        lastName: "Collins",
        email: "brandonanthonycollins@hotmail.com",
        birthDate: "1992-07-30",
        basicSalary: 18635800,
        status: "Active",
        group: "Supervisor",
        description: "2022-07-30"
    },
    {
        id: 22,
        username: "opencushion",
        firstName: "Rebecca",
        lastName: "Diaz",
        email: "r_j70@outlook.com",
        birthDate: "1991-05-12",
        basicSalary: 18410400,
        status: "Active",
        group: "Staff",
        description: "2011-05-12"
    },
    {
        id: 23,
        username: "steadystar",
        firstName: "Victoria",
        lastName: "Washington",
        email: "victoriarwashington@gmail.com",
        birthDate: "1989-05-02",
        basicSalary: 17439200,
        status: "Active",
        group: "Staff",
        description: "2010-05-02"
    },
    {
        id: 24,
        username: "learnedpocket",
        firstName: "Brian",
        lastName: "Lopez",
        email: "b_lopez41@rocketmail.com",
        birthDate: "1987-04-30",
        basicSalary: 20535600,
        status: "Active",
        group: "Manager",
        description: "2012-04-30"
    },
    {
        id: 25,
        username: "damagingstory",
        firstName: "Charlotte",
        lastName: "Rivera",
        email: "charlotte.m.rivera55@rocketmail.com",
        birthDate: "2003-06-15",
        basicSalary: 20759800,
        status: "Active",
        group: "Manager",
        description: "2023-06-15"
    },
    {
        id: 26,
        username: "magentaparcel",
        firstName: "Dylan",
        lastName: "Jackson",
        email: "d.jackson14@hotmail.com",
        birthDate: "1996-02-16",
        basicSalary: 19506400,
        status: "Active",
        group: "Staff",
        description: "2016-02-16"
    },
    {
        id: 27,
        username: "dampsound",
        firstName: "Audrey",
        lastName: "Clark",
        email: "a.clark@yahoo.com",
        birthDate: "1972-06-27",
        basicSalary: 18863500,
        status: "Active",
        group: "Supervisor",
        description: "2022-06-27"
    },
    {
        id: 28,
        username: "maddeningrange",
        firstName: "Brianna",
        lastName: "Cox",
        email: "briannacox90@aol.com",
        birthDate: "1994-02-02",
        basicSalary: 18665300,
        status: "Active",
        group: "Supervisor",
        description: "2013-02-02"
    },
    {
        id: 29,
        username: "somberkey",
        firstName: "Zachary",
        lastName: "Powell",
        email: "z.c.powell@hotmail.com",
        birthDate: "1969-01-16",
        basicSalary: 20301000,
        status: "Active",
        group: "Manager",
        description: "2018-01-16"
    },
    {
        id: 30,
        username: "interestingjewel",
        firstName: "Layla",
        lastName: "Bryant",
        email: "l_d_bryant@ymail.com",
        birthDate: "1994-10-23",
        basicSalary: 20247800,
        status: "Active",
        group: "Manager",
        description: "2021-10-23"
    },
    {
        id: 31,
        username: "delicatecontrol",
        firstName: "Stephanie",
        lastName: "Coleman",
        email: "s_coleman66@ymail.com",
        birthDate: "1972-05-09",
        basicSalary: 18174000,
        status: "Active",
        group: "Staff",
        description: "2023-05-09"
    },
    {
        id: 32,
        username: "receptivetooth",
        firstName: "Alexander",
        lastName: "Russell",
        email: "alexander_russell@rocketmail.com",
        birthDate: "1973-04-13",
        basicSalary: 20328400,
        status: "Active",
        group: "Manager",
        description: "2023-04-13"
    },
    {
        id: 33,
        username: "damagingtrain",
        firstName: "Michael",
        lastName: "Parker",
        email: "m.c.parker@gmail.com",
        birthDate: "1993-04-29",
        basicSalary: 19323800,
        status: "Active",
        group: "Supervisor",
        description: "2013-04-29"
    },
    {
        id: 34,
        username: "colossalsoup",
        firstName: "Layla",
        lastName: "Edwards",
        email: "layla@hotmail.com",
        birthDate: "2011-06-21",
        basicSalary: 19904200,
        status: "Active",
        group: "Staff",
        description: "2011-06-21"
    },
    {
        id: 35,
        username: "wrytrip",
        firstName: "Olivia",
        lastName: "Davis",
        email: "o.davis@aol.com",
        birthDate: "2004-05-02",
        basicSalary: 19620200,
        status: "Active",
        group: "Supervisor",
        description: "2018-05-02"
    },
    {
        id: 36,
        username: "averagejewel",
        firstName: "Isaac",
        lastName: "Rogers",
        email: "i_rogers@aol.com",
        birthDate: "1972-02-09",
        basicSalary: 18500800,
        status: "Active",
        group: "Manager",
        description: "2022-02-09"
    },
    {
        id: 37,
        username: "equablekey",
        firstName: "Elizabeth",
        lastName: "Collins",
        email: "elizabeth.collins@hotmail.com",
        birthDate: "1996-06-26",
        basicSalary: 18182600,
        status: "Active",
        group: "Staff",
        description: "2016-06-26"
    },
    {
        id: 38,
        username: "niceface",
        firstName: "Maria",
        lastName: "Green",
        email: "maria.m.green13@hotmail.com",
        birthDate: "1972-10-08",
        basicSalary: 19169400,
        status: "Active",
        group: "Staff",
        description: "2023-10-08"
    },
    {
        id: 39,
        username: "woozycreature",
        firstName: "Alyssa",
        lastName: "Cook",
        email: "acook@hotmail.com",
        birthDate: "2002-09-11",
        basicSalary: 18909900,
        status: "Active",
        group: "Supervisor",
        description: "2017-09-11"
    },
    {
        id: 40,
        username: "somberlanguage",
        firstName: "Layla",
        lastName: "Wilson",
        email: "l_wilson88@live.com",
        birthDate: "1990-06-10",
        basicSalary: 20164800,
        status: "Active",
        group: "Manager",
        description: "2010-06-10"
    },
    {
        id: 41,
        username: "knowledgeablebulb",
        firstName: "Taylor",
        lastName: "Smith",
        email: "taylorsmith76@hotmail.com",
        birthDate: "1992-08-25",
        basicSalary: 7326350,
        status: "Active",
        group: "Staff",
        description: "2016-08-25"
    },
    {
        id: 42,
        username: "roastedcable",
        firstName: "Mark",
        lastName: "Ramirez",
        email: "m.ramirez@rocketmail.com",
        birthDate: "1974-06-22",
        basicSalary: 11834800,
        status: "Terminated",
        group: "Supervisor",
        description: "2014-06-22"
    },
    {
        id: 43,
        username: "adorableshade",
        firstName: "James",
        lastName: "Adams",
        email: "jjadams@hotmail.com",
        birthDate: "1987-07-29",
        basicSalary: 14659700,
        status: "Terminated",
        group: "Supervisor",
        description: "2017-07-29"
    },
    {
        id: 44,
        username: "certainelbow",
        firstName: "Lillian",
        lastName: "Williams",
        email: "lillian.l.williams@rocketmail.com",
        birthDate: "1972-03-31",
        basicSalary: 18558600,
        status: "Terminated",
        group: "Manager",
        description: "2022-03-31"
    },
    {
        id: 45,
        username: "certainrainstorm",
        firstName: "Nicole",
        lastName: "Alexander",
        email: "nialexander8@yahoo.com",
        birthDate: "1999-05-29",
        basicSalary: 18067400,
        status: "Active",
        group: "Staff",
        description: "2019-05-29"
    },
    {
        id: 46,
        username: "nimblefrog",
        firstName: "Megan",
        lastName: "Brooks",
        email: "meganmaybrooks@gmail.com",
        birthDate: "1989-08-30",
        basicSalary: 20046300,
        status: "Active",
        group: "Staff",
        description: "2017-08-30"
    },
    {
        id: 47,
        username: "vivaciousstar",
        firstName: "Tiffany",
        lastName: "Anderson",
        email: "t_l_anderson@outlook.com",
        birthDate: "1973-09-21",
        basicSalary: 17855900,
        status: "Terminated",
        group: "Supervisor",
        description: "2013-09-21"
    },
    {
        id: 48,
        username: "unwrittenforce",
        firstName: "Claire",
        lastName: "Adams",
        email: "cadams@aol.com",
        birthDate: "1981-01-12",
        basicSalary: 11505600,
        status: "Active",
        group: "Staff",
        description: "2011-01-12"
    },
    {
        id: 49,
        username: "fiercetalk",
        firstName: "Mateo",
        lastName: "Henderson",
        email: "mateo.henderson12@aol.com",
        birthDate: "1978-05-18",
        basicSalary: 19354100,
        status: "Terminated",
        group: "Manager",
        description: "2014-05-18"
    },
    {
        id: 50,
        username: "mightystart",
        firstName: "Megan",
        lastName: "Evans",
        email: "meganjaneevans@aol.com",
        birthDate: "1973-10-27",
        basicSalary: 19772600,
        status: "Active",
        group: "Staff",
        description: "2019-10-27"
    },
    {
        id: 51,
        username: "gulliblelanguage",
        firstName: "Amelia",
        lastName: "Rodriguez",
        email: "amelia.r.rodriguez30@ymail.com",
        birthDate: "1971-10-11",
        basicSalary: 18974000,
        status: "Terminated",
        group: "Supervisor",
        description: "2011-10-11"
    },
    {
        id: 52,
        username: "zippynose",
        firstName: "Thomas",
        lastName: "Evans",
        email: "thomas.evans34@hotmail.com",
        birthDate: "1969-02-13",
        basicSalary: 20005000,
        status: "Terminated",
        group: "Manager",
        description: "2019-02-13"
    },
    {
        id: 53,
        username: "delicateswim",
        firstName: "Christopher",
        lastName: "Hughes",
        email: "c.a@aol.com",
        birthDate: "1970-04-13",
        basicSalary: 21315700,
        status: "Terminated",
        group: "Manager",
        description: "2020-04-13"
    },
    {
        id: 54,
        username: "feignedbridge",
        firstName: "Brianna",
        lastName: "Kelly",
        email: "brianna.kelly@gmail.com",
        birthDate: "1970-03-09",
        basicSalary: 12238000,
        status: "Terminated",
        group: "Manager",
        description: "2020-03-09"
    },
    {
        id: 55,
        username: "funnycoat",
        firstName: "Emily",
        lastName: "Lewis",
        email: "emily@ymail.com",
        birthDate: "1983-09-27",
        basicSalary: 12075200,
        status: "Terminated",
        group: "Manager",
        description: "2017-09-27"
    },
    {
        id: 56,
        username: "plainairplane",
        firstName: "Ashley",
        lastName: "Allen",
        email: "ashleyallen66@rocketmail.com",
        birthDate: "1992-01-20",
        basicSalary: 5846700,
        status: "Active",
        group: "Staff",
        description: "2012-01-20"
    },
    {
        id: 57,
        username: "chivalrousorder",
        firstName: "Jennifer",
        lastName: "Rodriguez",
        email: "j_rodriguez@aol.com",
        birthDate: "1993-06-28",
        basicSalary: 7370030,
        status: "Active",
        group: "Staff",
        description: "2012-06-28"
    },
    {
        id: 58,
        username: "yellowearth",
        firstName: "Joseph",
        lastName: "Perry",
        email: "joseph@ymail.com",
        birthDate: "1970-09-04",
        basicSalary: 6341400,
        status: "Terminated",
        group: "Manager",
        description: "2020-09-04"
    },
    {
        id: 59,
        username: "gulliblejeans",
        firstName: "Jessica",
        lastName: "Bennett",
        email: "j.bennett@gmail.com",
        birthDate: "1996-09-27",
        basicSalary: 7109730,
        status: "Terminated",
        group: "Manager",
        description: "2016-09-27"
    },
    {
        id: 60,
        username: "jazzyairplane",
        firstName: "Brianna",
        lastName: "Simmons",
        email: "briannasimmons@live.com",
        birthDate: "1973-03-08",
        basicSalary: 19384700,
        status: "Terminated",
        group: "Manager",
        description: "2023-03-08"
    },
    {
        id: 61,
        username: "largestar",
        firstName: "Katherine",
        lastName: "Turner",
        email: "katherinej75@rocketmail.com",
        birthDate: "1991-12-13",
        basicSalary: 17922700,
        status: "Active",
        group: "Manager",
        description: "2014-12-13"
    },
    {
        id: 62,
        username: "dynamicchicken",
        firstName: "Jason",
        lastName: "Richardson",
        email: "j.richardson64@aol.com",
        birthDate: "1981-12-09",
        basicSalary: 11384900,
        status: "Terminated",
        group: "Supervisor",
        description: "2015-12-09"
    },
    {
        id: 63,
        username: "feignedexistence",
        firstName: "Nicholas",
        lastName: "Wood",
        email: "n_wood@hotmail.com",
        birthDate: "1982-04-24",
        basicSalary: 19310200,
        status: "Terminated",
        group: "Manager",
        description: "2022-04-24"
    },
    {
        id: 64,
        username: "youthfulscience",
        firstName: "Sarah",
        lastName: "Gonzales",
        email: "sarahagonzales@outlook.com",
        birthDate: "1992-07-12",
        basicSalary: 20378200,
        status: "Active",
        group: "Staff",
        description: "2014-07-12"
    },
    {
        id: 65,
        username: "priceyfurniture",
        firstName: "Daniel",
        lastName: "Butler",
        email: "d.h@ymail.com",
        birthDate: "1973-04-05",
        basicSalary: 19116400,
        status: "Terminated",
        group: "Manager",
        description: "2023-04-05"
    },
    {
        id: 66,
        username: "simplisticshape",
        firstName: "Grace",
        lastName: "Clark",
        email: "gclark2@rocketmail.com",
        birthDate: "2009-10-18",
        basicSalary: 7134360,
        status: "Terminated",
        group: "Manager",
        description: "2019-10-18"
    },
    {
        id: 67,
        username: "chiefsteam",
        firstName: "Benjamin",
        lastName: "Thompson",
        email: "benjaminjthompson@aol.com",
        birthDate: "1971-04-29",
        basicSalary: 17637900,
        status: "Terminated",
        group: "Supervisor",
        description: "2021-04-29"
    },
    {
        id: 68,
        username: "unknownhook",
        firstName: "Nicole",
        lastName: "Wilson",
        email: "nicole@yahoo.com",
        birthDate: "2006-12-07",
        basicSalary: 9233310,
        status: "Active",
        group: "Staff",
        description: "2016-12-07"
    },
    {
        id: 69,
        username: "unknownsnow",
        firstName: "Dylan",
        lastName: "Wilson",
        email: "dylan@gmail.com",
        birthDate: "1976-07-09",
        basicSalary: 11743800,
        status: "Active",
        group: "Staff",
        description: "2021-07-09"
    },
    {
        id: 70,
        username: "adorableriddle",
        firstName: "Christopher",
        lastName: "Butler",
        email: "cbutler@ymail.com",
        birthDate: "1973-06-08",
        basicSalary: 17972200,
        status: "Active",
        group: "Staff",
        description: "2023-06-08"
    },
    {
        id: 71,
        username: "somberelbow",
        firstName: "Stephen",
        lastName: "Edwards",
        email: "s_f_edwards4@aol.com",
        birthDate: "1974-02-23",
        basicSalary: 11775100,
        status: "Terminated",
        group: "Manager",
        description: "2010-02-23"
    },
    {
        id: 72,
        username: "naturalnose",
        firstName: "Emma",
        lastName: "Taylor",
        email: "e_taylor43@hotmail.com",
        birthDate: "1970-10-10",
        basicSalary: 19263500,
        status: "Active",
        group: "Staff",
        description: "2016-10-10"
    },
    {
        id: 73,
        username: "wickedwren",
        firstName: "Jason",
        lastName: "Jenkins",
        email: "jasonjenkins@yahoo.com",
        birthDate: "2001-07-14",
        basicSalary: 7199780,
        status: "Active",
        group: "Staff",
        description: "2011-07-14"
    },
    {
        id: 74,
        username: "receptiverock",
        firstName: "Elizabeth",
        lastName: "Young",
        email: "eyoung@aol.com",
        birthDate: "2006-12-17",
        basicSalary: 14676500,
        status: "Terminated",
        group: "Manager",
        description: "2010-12-17"
    },
    {
        id: 75,
        username: "calculatingbehavior",
        firstName: "Michael",
        lastName: "Ramirez",
        email: "michaelramirez@ymail.com",
        birthDate: "1981-05-26",
        basicSalary: 12655200,
        status: "Active",
        group: "Staff",
        description: "2022-05-26"
    },
    {
        id: 76,
        username: "harshair",
        firstName: "Kyle",
        lastName: "Griffin",
        email: "k.griffin@yahoo.com",
        birthDate: "1970-01-09",
        basicSalary: 11987500,
        status: "Terminated",
        group: "Manager",
        description: "2021-01-09"
    },
    {
        id: 77,
        username: "breezyroof",
        firstName: "Christopher",
        lastName: "Hernandez",
        email: "c.hernandez@aol.com",
        birthDate: "1988-11-15",
        basicSalary: 13166700,
        status: "Terminated",
        group: "Manager",
        description: "2012-11-15"
    },
    {
        id: 78,
        username: "delicatebit",
        firstName: "Mary",
        lastName: "Russell",
        email: "mary@rocketmail.com",
        birthDate: "1993-10-30",
        basicSalary: 12596300,
        status: "Active",
        group: "Staff",
        description: "2013-10-30"
    },
    {
        id: 79,
        username: "harshshake",
        firstName: "Amelia",
        lastName: "Roberts",
        email: "a_roberts@live.com",
        birthDate: "1974-08-14",
        basicSalary: 0,
        status: "Terminated",
        group: "Manager",
        description: "2020-08-14"
    },
    {
        id: 80,
        username: "seemlyhope",
        firstName: "Aiden",
        lastName: "Washington",
        email: "awashington@rocketmail.com",
        birthDate: "1971-02-09",
        basicSalary: 18305000,
        status: "Active",
        group: "Manager",
        description: "2022-02-09"
    },
    {
        id: 81,
        username: "maddeningscarf",
        firstName: "William",
        lastName: "Hall",
        email: "w.hall23@live.com",
        birthDate: "1984-11-26",
        basicSalary: 20809900,
        status: "Active",
        group: "Manager",
        description: "2010-11-26"
    },
    {
        id: 82,
        username: "feignedairplane",
        firstName: "Sara",
        lastName: "Hall",
        email: "s.hall@outlook.com",
        birthDate: "1986-08-01",
        basicSalary: 12584200,
        status: "Terminated",
        group: "Supervisor",
        description: "2011-08-01"
    },
    {
        id: 83,
        username: "steadyearth",
        firstName: "Aaron",
        lastName: "Campbell",
        email: "aaron_campbell@live.com",
        birthDate: "1975-08-19",
        basicSalary: 20174500,
        status: "Terminated",
        group: "Manager",
        description: "2023-08-19"
    },
    {
        id: 84,
        username: "painstakingocean",
        firstName: "Jack",
        lastName: "Cox",
        email: "j.cox@gmail.com",
        birthDate: "1993-11-05",
        basicSalary: 18591400,
        status: "Terminated",
        group: "Manager",
        description: "2023-11-05"
    },
    {
        id: 85,
        username: "bouncysnow",
        firstName: "Christopher",
        lastName: "Barnes",
        email: "christopher_r_barnes@ymail.com",
        birthDate: "1988-02-04",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2014-02-04"
    },
    {
        id: 86,
        username: "charmingsnow",
        firstName: "Samuel",
        lastName: "Williams",
        email: "sm@ymail.com",
        birthDate: "1973-11-06",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2019-11-06"
    },
    {
        id: 87,
        username: "faintroof",
        firstName: "Sara",
        lastName: "Williams",
        email: "s_williams@ymail.com",
        birthDate: "1989-06-22",
        basicSalary: 10454200,
        status: "Terminated",
        group: "Manager",
        description: "2010-06-22"
    },
    {
        id: 88,
        username: "prettymarket",
        firstName: "Charles",
        lastName: "Allen",
        email: "c_e18@ymail.com",
        birthDate: "1989-07-18",
        basicSalary: 18795400,
        status: "Terminated",
        group: "Manager",
        description: "2010-07-18"
    },
    {
        id: 89,
        username: "incandescenttrain",
        firstName: "Joshua",
        lastName: "Cook",
        email: "j.j.cook79@ymail.com",
        birthDate: "1971-01-27",
        basicSalary: 0,
        status: "Terminated",
        group: "Manager",
        description: "2019-01-27"
    },
    {
        id: 90,
        username: "dullcontrol",
        firstName: "Emma",
        lastName: "Powell",
        email: "e.m.powell@gmail.com",
        birthDate: "1994-02-21",
        basicSalary: 7775830,
        status: "Terminated",
        group: "Manager",
        description: "2015-02-21"
    },
    {
        id: 91,
        username: "enchantinglamp",
        firstName: "Maria",
        lastName: "Bailey",
        email: "maria@ymail.com",
        birthDate: "1971-01-03",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2012-01-03"
    },
    {
        id: 92,
        username: "highfalutintheory",
        firstName: "Kyle",
        lastName: "Allen",
        email: "k_allen@outlook.com",
        birthDate: "1978-01-30",
        basicSalary: 18727800,
        status: "Terminated",
        group: "Manager",
        description: "2017-01-30"
    },
    {
        id: 93,
        username: "stickyearth",
        firstName: "Tyler",
        lastName: "Young",
        email: "tyler@gmail.com",
        birthDate: "1985-11-23",
        basicSalary: 12874700,
        status: "Terminated",
        group: "Manager",
        description: "2011-11-23"
    },
    {
        id: 94,
        username: "somberarm",
        firstName: "Charles",
        lastName: "Williams",
        email: "charles.williams52@live.com",
        birthDate: "1970-12-12",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2013-12-12"
    },
    {
        id: 95,
        username: "jazzystar",
        firstName: "Charles",
        lastName: "Murphy",
        email: "charles_r_murphy@live.com",
        birthDate: "1982-11-02",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2015-11-02"
    },
    {
        id: 96,
        username: "joyouspin",
        firstName: "Amber",
        lastName: "Jenkins",
        email: "a.m.jenkins@rocketmail.com",
        birthDate: "1970-11-06",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2023-11-06"
    },
    {
        id: 97,
        username: "yellowsmile",
        firstName: "Lauren",
        lastName: "Murphy",
        email: "l_n_murphy76@yahoo.com",
        birthDate: "1986-11-27",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2011-11-27"
    },
    {
        id: 98,
        username: "bewilderedmitten",
        firstName: "Kyle",
        lastName: "Washington",
        email: "kyle_h_washington@rocketmail.com",
        birthDate: "1974-03-09",
        basicSalary: 0,
        status: "Active",
        group: "Staff",
        description: "2018-03-09"
    },
    {
        id: 99,
        username: "interestingrainstorm",
        firstName: "Adam",
        lastName: "Jenkins",
        email: "a_jenkins@hotmail.com",
        birthDate: "1989-01-16",
        basicSalary: 19260400,
        status: "Terminated",
        group: "Manager",
        description: "2014-01-16"
    },
    {
        id: 100,
        username: "learnedrailway",
        firstName: "Victoria",
        lastName: "Anderson",
        email: "victoria.k.anderson96@yahoo.com",
        birthDate: "1994-07-19",
        basicSalary: 19988900,
        status: "Active",
        group: "Supervisor",
        description: "2014-07-19"
    }
]